project: sam
group: debug

trainer:
  max_epochs: 20

sam:
  adaptive: false
  rho: 0.05

loss:
  kl_cycle: 5
  kl_weight: 0.2
  l1_weight: 0.5
  trans_vae_cond_weight: 0.5
  affine_weight: 0.2
  spectral_weight: 0.2
