project: r252_sam
group: mobilenetv3_finetune

trainer:
  max_epochs: 5

model:
  model_cls: MobileNetV3

optimizer:
  lr: 1e-3

data:
  use_cutout: false
  use_autoaugment: false

sam:
  use_sam: false