project: r252_sam
group: mobilenetv3_finetune_sam

trainer:
  max_epochs: 150

model:
  model_cls: MobileNetV3

optimizer:
  lr: 1e-3

data:
  use_cutout: false
  use_autoaugment: false
  train_batch_size: 128

sam:
  use_sam: true