project: r252_sam
group: mobilenetv2_sgd_sam

trainer:
  max_epochs: 200

model:
  model_cls: MobileNetV2

data:
  train_batch_size: 50000
  use_cutout: true
  use_autoaugment: true

sam:
  use_sam: true
  adaptive: false
  rho: 0.1