project: r252_sam
group: mobilenetv2_rp

trainer:
  trainer: RPTrainer
  max_epochs: 400

model:
  model_cls: MobileNetV2

data:
  train_batch_size: 128
  use_cutout: true
  use_autoaugment: true

sam:
  rho: 1.0