project: r252_sam
group: sam

trainer:
  max_epochs: 500

model:
  model_cls: MobileNetV3
  mobile_net_pretrained: false
  num_outputs: 10

data:
  use_cutout: false
  use_autoaugment: false
  train_batch_size: 128
  samples_per_class: 250

sam:
  use_sam: true
  adaptive: false
  rho: 0.05

